Repository fylein/fyle-partner-dashboard-app, pull requests merged in 2025-03, with the labels that each got.

#102 fix: outdated packages
  .gitignore
  package-lock.json
  package.json
  src/app/shared/components/home/client-table/client-table.component.html
  src/main.ts
Labels: deploy, size/XL

#103 chore: package upgrades
  package-lock.json
  package.json
Labels: size/S

#105 fix: help domain change
  src/app/core/models/enum/enum.model.ts
Labels: size/XS

#106 fix: Run container with non root user
  Dockerfile
Labels: size/XS

#108 fix: Revert change
  Dockerfile
Labels: size/XS

#110 feat: Add action for EOL and Outdated JS
  .github/workflows/eol-outdated-js-scan.yml
  suppression.xml
Labels: size/M

#109 fix: Run container with non root user - 1
  Dockerfile
  nginx.conf
Labels: deploy, size/S
