Repository fylein/fyle-partner-dashboard-app, pull requests merged in 2025-02, with the labels that each got.

#97 chore: Remove PII info for external apps
  src/app/core/services/integration/tracking.service.spec.ts
  src/app/core/services/integration/tracking.service.ts
  src/app/partner/partner.component.ts
Labels: size/S

#100 fix: remove unused cypress
  .browserslistrc
  .github/workflows/lint.yml
  .github/workflows/production-deployment.yml
  .github/workflows/staging-deployment.yml
  .github/workflows/unit-test.yml
  Dockerfile
  angular.json
  cypress/coverage.webpack.js
  cypress/coverage/coverage-summary.json
  cypress/e2e/001-micro-actions/001-auth-login.cy.js
  cypress/e2e/001-micro-actions/002-auth-logout.cy.js
  cypress/e2e/001-micro-actions/003-simple-search.cy.js
  cypress/e2e/001-micro-actions/004-paginator.cy.js
  cypress/e2e/001-micro-actions/005-detail-view.cy.js
  cypress/e2e/001-micro-actions/006-table-view.cy.js
  cypress/package-lock.json
  cypress/package.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/fyle-callback/fyle-callback.component.spec.ts
  src/app/auth/login/login.component.spec.ts
  src/app/auth/logout/logout.component.spec.ts
  src/app/core/guard/auth.guard.spec.ts
  src/app/core/guard/auth.guard.ts
  src/app/core/interceptors/jwt.interceptor.spec.ts
  src/app/core/interceptors/jwt.interceptor.ts
  src/app/core/services/core/api.service.spec.ts
  src/app/core/services/core/api.service.ts
  src/app/core/services/core/auth.service.spec.ts
  src/app/core/services/core/auth.service.ts
  src/app/core/services/core/partner.service.spec.ts
  src/app/core/services/home/home.service.spec.ts
  src/app/core/services/misc/user.service.spec.ts
  src/app/partner/home/home.component.html
  src/app/partner/home/home.component.spec.ts
  src/app/partner/home/home.component.ts
  src/app/partner/partner.component.spec.ts
  src/app/shared/components/core/header/header.component.spec.ts
  src/app/shared/components/core/help-dropdown/help-dropdown.component.html
  src/app/shared/components/core/profile-dropdown/profile-dropdown.component.spec.ts
  src/app/shared/components/helpers/paginator/paginator.component.html
  src/app/shared/components/home/client-card/client-card.component.scss
  src/app/shared/components/home/client-card/client-card.component.spec.ts
  src/app/shared/components/home/client-table/client-table.component.html
  src/app/shared/components/home/client-table/client-table.component.scss
  src/app/shared/components/home/client-table/client-table.component.spec.ts
  src/main.ts
  src/styles.scss
  src/test.ts
  tailwind.config.js
  tsconfig.json
Labels: deploy, size/XL

#101 fix: esbuilt version fix
  package-lock.json
  package.json
Labels: size/XL
