Repository fylein/fyle-partner-dashboard-app, pull requests merged in 2025-06, with the labels that each got.

#118 feat: add Gitleaks secrets scan workflow
  .github/workflows/secrets-scan.yaml
Labels: size/S

#120 feat: i18n changes
  .gitignore
  angular.json
  package-lock.json
  package.json
  scripts/i18n/i18n_extraction.py
  scripts/i18n/inline_and_diff.py
  scripts/i18n/list_source_files.py
  scripts/i18n/write_updated_files.py
  src/app/app.module.ts
  src/app/auth/auth.component.html
  src/app/auth/fyle-callback/fyle-callback.component.ts
  src/app/auth/login/login.component.html
  src/app/partner/home/home.component.html
  src/app/shared/components/core/header/header.component.html
  src/app/shared/components/core/help-dropdown/help-dropdown.component.html
  src/app/shared/components/core/help-dropdown/help-dropdown.component.ts
  src/app/shared/components/core/profile-dropdown/profile-dropdown.component.html
  src/app/shared/components/helpers/paginator/paginator.component.html
  src/app/shared/components/helpers/paginator/paginator.component.ts
  src/app/shared/components/helpers/simple-search-text/simple-search-text.component.html
  src/app/shared/components/home/client-card/client-card.component.html
  src/app/shared/components/home/client-card/client-card.component.ts
  src/app/shared/components/home/client-table/client-table.component.html
  src/app/shared/components/home/client-table/client-table.component.ts
  src/app/shared/shared.module.ts
  src/app/transloco-http-loader.ts
  src/assets/i18n/en.json
Labels: deploy, size/XL

#122 chore: remove security scan workflow
  .github/workflows/security-scan.yml
Labels: size/S

#124 feat: Add codeowners file
  .github/CODEOWNERS
Labels: size/XS
